name: psalm

on:
    push:
        paths:
            - '**.php'
            - 'psalm.xml'
            - '.github/workflows/psalm.yml'

jobs:
    psalm:
        name: psalm
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '7.4'
                  extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, redis
                  coverage: none

            - name: Cache composer dependencies
              uses: actions/cache@v1
              with:
                  path: vendor
                  key: composer-${{ hashFiles('composer.lock') }}

            - name: Run composer install
              env:
                NOVA_USERNAME: ${{ secrets.NOVA_USERNAME }}
                NOVA_PASSWORD: ${{ secrets.NOVA_PASSWORD }}
              run: |
                composer config http-basic.nova.laravel.com $NOVA_USERNAME $NOVA_PASSWORD
                composer install -n --prefer-dist

            - name: Run psalm
              run: ./vendor/bin/psalm -c psalm.xml --show-info=true
