name: tests

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest ]
        php: [7.4, 8.0]
        laravel: [ 6.*, 8.* ]
        dependency-version: [ prefer-stable ]
        include:
          - laravel: 6.*
            testbench: 4.*

          - laravel: 8.*
            testbench: 6.*

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, intl, exif
          coverage: none

      - name: Install dependencies
        env:
          NOVA_USERNAME: ${{ secrets.NOVA_USERNAME }}
          NOVA_PASSWORD: ${{ secrets.NOVA_PASSWORD }}
        run: |
          composer config http-basic.nova.laravel.com $NOVA_USERNAME $NOVA_PASSWORD
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest

      - name: Execute tests
        env:
          CODACY_API_TOKEN: ${{ secrets.CODACY_API_TOKEN }}
          CODACY_USERNAME: "d8vjork"
          CODACY_PROJECT_NAME: "laravel-status"
        run: |
          cp phpunit.dist.xml phpunit.xml || true
          vendor/bin/phpunit
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report -a $CODACY_API_TOKEN -u $CODACY_USERNAME -p $CODACY_PROJECT_NAME --organization-provider github -l php
